// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5571UXjSX-6eJ8Fgua7e2DPifb7VbhVE',
    appId: '1:575968351869:web:435d3a8911e901f93bc314',
    messagingSenderId: '575968351869',
    projectId: 'sakecbuddy-1022',
    authDomain: 'sakecbuddy-1022.firebaseapp.com',
    storageBucket: 'sakecbuddy-1022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRuGMdYjAyV225Fu6_tAtBYn963LpWLs',
    appId: '1:575968351869:android:5a5a87db6e53f1583bc314',
    messagingSenderId: '575968351869',
    projectId: 'sakecbuddy-1022',
    storageBucket: 'sakecbuddy-1022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgb91cd38tEquVJHvVv388T-PVf5CEYvU',
    appId: '1:575968351869:ios:fb40580837f5882e3bc314',
    messagingSenderId: '575968351869',
    projectId: 'sakecbuddy-1022',
    storageBucket: 'sakecbuddy-1022.appspot.com',
    iosBundleId: 'com.example.sakecBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgb91cd38tEquVJHvVv388T-PVf5CEYvU',
    appId: '1:575968351869:ios:fb40580837f5882e3bc314',
    messagingSenderId: '575968351869',
    projectId: 'sakecbuddy-1022',
    storageBucket: 'sakecbuddy-1022.appspot.com',
    iosBundleId: 'com.example.sakecBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5571UXjSX-6eJ8Fgua7e2DPifb7VbhVE',
    appId: '1:575968351869:web:97d456ebfb6dfa793bc314',
    messagingSenderId: '575968351869',
    projectId: 'sakecbuddy-1022',
    authDomain: 'sakecbuddy-1022.firebaseapp.com',
    storageBucket: 'sakecbuddy-1022.appspot.com',
  );
}
